In [1]:
import numpy as np
import scipy as sp
import util

[[1 1 1 1 0 0]
 [0 1 1 0 1 0]
 [0 0 1 1 0 1]]
[[1 0 0 1 1 0]
 [0 1 0 1 1 1]
 [0 0 1 1 0 1]]
[[1 1 0 1 0 0]
 [1 1 1 0 1 0]
 [1 0 1 0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 0. 1.]]


<h1> Computing the generator matrix </h1>

The parity check matrix $\mathbf{H}$ has size (N-K,N) for a given K (message size) and N (codeword size) where K < N.
This check matrix defines a linear code, where the set of all possible codewords are vectors $\mathbf{x}$ such that $\mathbf{Hx} = 0$. In other words, the nullspace of $\mathbf{H}$ gives us the codebook. For which we need to have a mapping from the original message to the encoded vectors.

Since the code forms a K-dimensional subspace of $\{0,1\}^N$, we want to find the basis vectors of this subspace. Then, we can build a generator matrix $\mathbf{G}$, such that the codeword is just the message expressed in the basis defined by $\mathbf{G}$, i.e. $\mathbf{x} = \mathbf{Gt}$.

Using the rank-nullity theorem, we derive that the nullspace of $\mathbf{H}$ is K-dimensional, and so the columns of $\mathbf{G}$ are just K vectors that define the nullspace of $\mathbf{H}$.

In [2]:
# define parity check matrix
H = np.array([
    [1,1,1,1,0,0],
    [0,0,1,1,0,1],
    [1,0,0,1,1,0]
])

H_perm, G = util.generate_encoder(H)
print(G)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 0. 1.]]


In [3]:
H_perm

array([[1, 1, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 1]])

In [4]:
# generate some random ts and assert H_hat @ G @ t = 0
ts = np.random.randint(0, 2, size=9).reshape((3, 3))
print(ts)

[[1 1 1]
 [0 0 0]
 [1 0 1]]


In [7]:
for t in ts:
    print((H_perm @ G @ t) % 2)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]
