In [9]:
import numpy as np
import util

<h1> Computing the generator matrix </h1>

The parity check matrix $\mathbf{H}$ has size (N-K,N) for a given K (message size) and N (codeword size) where K < N.
This check matrix defines a linear code, where the set of all possible codewords are vectors $\mathbf{x}$ such that $\mathbf{Hx} = 0$. In other words, the nullspace of $\mathbf{H}$ gives us the codebook. For which we need to have a mapping from the original message to the encoded vectors.

Since the code forms a K-dimensional subspace of $\{0,1\}^N$, we want to find the basis vectors of this subspace. Then, we can build a generator matrix $\mathbf{G}$, such that the codeword is just the message expressed in the basis defined by $\mathbf{G}$, i.e. $\mathbf{x} = \mathbf{Gt}$.

Using the rank-nullity theorem, we derive that the nullspace of $\mathbf{H}$ is K-dimensional, and so the columns of $\mathbf{G}$ are just K vectors that define the nullspace of $\mathbf{H}$.

In [12]:
# define parity check matrix
H = np.array([
    [1,1,1,1,0,0],
    [0,0,1,1,0,1],
    [1,0,0,1,1,0]
])

H_perm, G = util.generate_encoder(H)
print(H_perm)
print(G)

[[1 1 0 1 0 0]
 [1 1 1 0 1 0]
 [1 0 1 0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 0. 1.]]


We can check if our generator matrix produces a valid code by checking $\hat{\mathbf{H}} \mathbf{G} \mathbf{t} = 0$ $\forall \mathbf{t}$.

In [3]:
# generate some random ts and assert H_hat @ G @ t = 0
ts = np.random.randint(0, 2, size=9).reshape((3, 3))

for t in ts:
    print((H_perm @ G @ t) % 2)

[0. 0. 0.]
[0. 0. 0.]
[0. 0. 0.]


<h1> Decoding</h1>

Given a parity check matrix and a recieved codeword from the noisy channel we are modelling, we can use loopy belief propagation as shown in Shokrollahi, LDPC Codes: an Introduction to approximately infer the most likely codeword.

In [4]:
H = np.loadtxt("H1.txt")
y = np.loadtxt("y1.txt")

In [7]:
info, decoded = util.ldpc_decode(H, y, 0.1, 20)

currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7


In the given text file, we are told that the first 248 bits should be interpreted as a sequence of 31 ASCII symbols

In [8]:
if info['SUCCESS_CODE'] == 0:
    print("---- SUCCESSFUL -----")

    original_msg = bytearray(np.packbits(decoded[:248])).decode().strip("\x00")
    print(f"The decoded message is: {original_msg}")
    print(f"number of iterations needed: {info['NUM_ITER']}")
else:
    print("---- UNSUCCESSFUL -----")

---- SUCCESSFUL DECODING -----
The decoded message is: Happy Holidays! Dmitry&David :)
number of iterations needed: 7


<h3> Just for checking performance </h3>

In [11]:
%timeit util.ldpc_decode(H, y, 0.1, 20)

currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
currently on step 2
currently on step 3
currently on step 4
currently on step 5
currently on step 6
currently on step 7
currently on step 1
